### ISSUE TITLE
SUID and SGID cannot be set

### ISSUE THREAD

**Issue by karkcoder** [spritsail/plex-media-server#38]
I cannot set the SUID and SGID. It is setting back to 900 which I believe is the default here. Is there a way to set to 1000? 

Error I am getting ... host and group id is 1000
Jan 05, 2022 02:18:01.025 [0x7fbd5f3b06e8] ERROR - IsFileWritable: failed to create file '"/transcode/689019a8-0626-46a3-a8d7-b0dfbefcc548"'

Below is my docker compose file ...

version: "2.1"
services:
  plex:
    image: spirit/plex-media-server
    container_name: plex-amd
    network_mode: host
    environment:
      - SUID:1000
      - SGID:1000
    volumes:
      -  /home/firestorm/plex/config:/config
      -  /home/firestorm/plex/transcode:/transcode
      -  /mnt/NAS:/media
      -  /dev/dri:/dev/dri
    restart: unless-stopped

**Comment by frebib** [comment]
With the docker-compose file you provided (with the typos fixed), Plex starts and runs as uid 1000. I do see the following warnings about /transcode not being writeable, although that's because Docker created that directory as owned by `root:root`
```
frebib@frebib-PC /t/tmp.oy4rCCI0> rg /transcode config/Logs/Plex\ Media\ Server.log
2180:Jan 05, 2022 19:46:17.287 [0x7f71b6af86e8] ERROR - IsFileWritable: failed to create file '"/transcode/0821d080-fd6e-4cbe-acf8-8f9e1ded3195"'
2181:Jan 05, 2022 19:46:17.287 [0x7f71b6af86e8] WARN - IsDirWritable: directory '"/transcode"' is not writable
```
```
frebib@frebib-PC /t/tmp.oy4rCCI0> l
total 4.0K
drwxr-xrwx 8 frebib frebib 180 Jan  5 19:46 config/
drwxr-xr-x 2 root   root    40 Jan  5 19:46 transcode/
-rw-r--r-- 1 frebib frebib 262 Jan  5 19:46 docker-compose.yml
```

If I chown the directory and restart plex, the error goes away.

Here is the full compose file I tested with, from your example above.
```
version: "2.1"

services:
  plex:
    image: spritsail/plex-media-server
    network_mode: host
    environment:
    - SUID=1000
    - SGID=1000
    volumes:
    - ./config:/config
    - ./transcode:/transcode
    - /dev/dri:/dev/dri
    restart: unless-stopped
```

I might suggest you exec into the container and check the permissions:
```
frebib@frebib-PC /t/tmp.oy4rCCI0> docker exec -ti tmpoy4rcci0-plex-1 su-exec 1000:1000 sh          
/usr/lib/plexmediaserver $ id
uid=1000 gid=1000 groups=1000
/usr/lib/plexmediaserver $ ls -al /transcode/
total 4
drwxr-xr-x    3 1000     1000            60 Jan  5 19:49 .
drwxr-xr-x    1 0        0             4096 Jan  5 19:52 ..
drwxr-xr-x    3 1000     1000            60 Jan  5 19:49 Transcode
/usr/lib/plexmediaserver $ touch /transcode/test
/usr/lib/plexmediaserver $
```
